export const MENU = [
  {
    id: '1',
    name: 'Chicken Wings',
    price: 6000,
    imageUrl: 'https://source.unsplash.com/900x900/?chicken',
    type: 'main',
    quantity: 1,
  },
  {
    id: '2',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '3',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '4',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '5',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
];
