import { Item } from 'app';

export const MENU: Item[] = [
  {
    id: '1',
    name: 'Chicken Wings',
    price: 6000,
    imageUrl: 'https://source.unsplash.com/900x900/?chicken',
    type: 'main',
    quantity: 1,
  },
  {
    id: '2',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '3',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '4',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '5',
    name: 'Fried Rice',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?rice',
    type: 'main',
    quantity: 1,
  },
  {
    id: '6',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '7',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '8',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '9',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '10',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '11',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '12',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '13',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '14',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '15',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '16',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '17',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '18',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '19',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '20',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '21',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
  {
    id: '22',
    name: 'Beans',
    price: 2500,
    imageUrl: 'https://source.unsplash.com/900x900/?beans',
    type: 'main',
    quantity: 1,
  },
];
